kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: api-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }} 
      http:
        paths:
          - path: /
            backend:
              serviceName: server
              servicePort: {{ .Values.server.port }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }} 
      secretName: tls-secret 
---
kind: Service
apiVersion: v1
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
spec:
  replicas: {{ .Values.server.replicas }} 
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.port }}
          readinessProbe:
            httpGet:
              path: /healthy
              port: {{ .Values.server.port }}
          imagePullPolicy: Always
          command:
            - "python3"
            - "-u"
            - "/app/src/python/server/app.py"
            - "--port={{ .Values.server.port }}"
      imagePullSecrets:
        - name: acr-creds
